# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ffe7d14daabd2758bc19a5f1b9f07c74a18b836180951257708484423b41a3be4cc3aa63c07b84532aa64cf0c7f8d9aade010ec5bc6af9c67586790ae4baf8

test:
  secret_key_base: 68412f0f18739d89b48f18efe658b09814745b2cceb4828a10583c7e43bb61a369d192cf470b289823233f8123a5afb446576a856e30fe2d879ec7364a0b8249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
